title: Chenlijia's Homepage
page-top-title: CHEN LIJIA
top-section-bg-text: Be what you wanna be
home-subtitle: chenlijia&ensp;|&ensp;2
copyright-text: '&copy; CHENLIJIA 2023-2025. All Rights Reserved.'
